# Generated by Django 6.0 on 2026-01-31 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('meeting_time', models.DateTimeField()),
                ('service', models.CharField(choices=[('personal_tax', 'Personal Tax'), ('corp_tax', 'Corporation Tax'), ('payroll', 'Payroll')], max_length=20)),
                ('new_client', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
